### ISSUE TITLE
Mark homework 1 exercise 1 and 2 of Maria Kamenetsky

### ISSUE THREAD

**Issue by mkamenet3** [mkamenet3/Stat679#1]
Hello Professor! Please find here the code to HW1, exercises 1 and 2. Thank you!
@cecileane
-Maria

https://github.com/mkamenet3/Stat679/tree/d03c66a19b0c197c0cb8b216e75f0319212fa171

What I did:
- scripts are run from the main 'hw1' directory and can run: 'source scripts/normalizeFileNames.sh' for HW1, Ex1 and 'source scripts/summaraizeSNAqres.sh' for HW1, Ex2.
- I used the approach where I create intermediate .csv files, then merge them into one master file, and delete the intermediate files (and substitute in a header file into master). The output file for HW1, Ex2 is 'master.csv' and is found in 'output/summaryFiles/master.csv'

**Comment by cecileane** [comment]
Hi Maria,

Great job! I like how you gave a high-level description of your coding strategy. I also like how you organized your files in subdirectories, and made the effort to write a readme file in each, with appropriate information. Your scripts have comments on the code itself, great job.

You used tons of different tools! From parameter substitution to `paste`, `grep`, `sed` and `awk`. Great job! You also did a fair use of extended regular expressions, which was one of the mail goals of the exercise.

In your summarizing script, the line to add the header at the end (with `sed`) could have been replaced by a simple `echo` command at the beginning, also replacing the 3 `touch` commands, just to simplify the code and to eliminate an intermediate file. (`echo "whatever" > filename` would create a file called `filename`). When dealing with large files, it's always interesting to eliminate large intermediates.

Your `sed` command
 `sed 1i"analysis,h,CPUtime" output/summary.csv > output/summaryFiles/master.csv`
assumes GNU `sed`. I got an error when running it:

``` shell
$ source scripts/summarizeSNaQres.sh
sed: 1: "1ianalysis,h,CPUtime": command i expects \ followed by text
```

The BSD `sed` requires a more complex syntax: with the `1i` followed by a slash and a newline. The GNU version does not require this more complex syntax. So after I edited your script to change `sed` to `gsed` (to get the GNU version), it all worked fine. You did document that your script was developed under the cygwin shell, which is good. Anyway, portability is another reason to try and simplify the code when possible.

Unfortunately, your code only looks at the files named "timetest*", excluding 3 other pairs of analysis files: `bT1`, and 2 others. I saw that you current solution to exercise 3 has the same limitation. It would be cool if you could remove this limitation for exercise 3!

Please close this issue, or [assign](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) it to me and I can close it.
